#!/usr/bin/env node
/**
 * Generates `dist/_headers` after a build.
 *
 * Two problems it solves:
 *
 * 1. **No security headers.** Workers Static Assets sends none by default.
 * 2. **`Cache-Control: public, max-age=0, must-revalidate` on everything.**
 *    That default is right for HTML (content changes without the URL changing)
 *    and wrong for content-hashed bundles, where it costs a revalidation
 *    round-trip on every visit for a file that can never change.
 *
 * The CSP is built from **hashes of the actual inline scripts in the output**,
 * not `'unsafe-inline'`. Hashes are recomputed here on every build, so editing
 * an inline script cannot silently break the policy or tempt anyone to loosen it.
 *
 * Header rules in `_headers` are APPENDED, not overridden — a later block does
 * not replace an inherited value. `! Cache-Control` explicitly clears the
 * inherited one before a sub-path sets its own.
 */
import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs'
import { join } from 'node:path'
import { createHash } from 'node:crypto'

const DIST = 'dist'

function htmlFiles(dir, acc = []) {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry)
    if (statSync(full).isDirectory()) htmlFiles(full, acc)
    else if (entry.endsWith('.html')) acc.push(full)
  }
  return acc
}

/** sha256-base64 of every inline <script> body found in the build. */
function inlineScriptHashes() {
  const hashes = new Set()
  for (const file of htmlFiles(DIST)) {
    const html = readFileSync(file, 'utf8')
    for (const m of html.matchAll(/<script(?![^>]*\bsrc=)[^>]*>([\s\S]*?)<\/script>/g)) {
      const body = m[1]
      if (body === undefined || body.trim() === '') continue
      hashes.add(`'sha256-${createHash('sha256').update(body, 'utf8').digest('base64')}'`)
    }
  }
  return [...hashes].sort()
}

/** Inline styles come from Astro's scoped <style> blocks. */
function inlineStyleHashes() {
  const hashes = new Set()
  for (const file of htmlFiles(DIST)) {
    const html = readFileSync(file, 'utf8')
    for (const m of html.matchAll(/<style[^>]*>([\s\S]*?)<\/style>/g)) {
      const body = m[1]
      if (body === undefined || body.trim() === '') continue
      hashes.add(`'sha256-${createHash('sha256').update(body, 'utf8').digest('base64')}'`)
    }
  }
  return [...hashes].sort()
}

const scriptHashes = inlineScriptHashes()
const styleHashes = inlineStyleHashes()

const csp = [
  "default-src 'none'",
  // 'wasm-unsafe-eval' is required for Pagefind: instantiating a WebAssembly
  // module is blocked by default, and without it search fails silently with
  // "Failed to load the Pagefind WASM" — verified in a real browser.
  //
  // This is deliberately NOT 'unsafe-eval'. The narrow keyword permits
  // WebAssembly compilation only; eval() of JavaScript strings stays blocked,
  // which is the property that actually matters for XSS.
  `script-src 'self' 'wasm-unsafe-eval' ${scriptHashes.join(' ')}`,
  // Astro emits scoped <style> blocks per page. Hashing them keeps
  // 'unsafe-inline' out of the policy.
  `style-src 'self' ${styleHashes.join(' ')}`,
  // `style-src-attr` governs `style="..."` ATTRIBUTES specifically. It must be
  // 'unsafe-inline' because KaTeX lays out every equation with inline styles
  // (height, margin-right, top on hundreds of spans per page) — a hash-based
  // policy cannot cover them, since CSP hashes do not apply to attributes.
  //
  // The residual risk is small and bounded: style attributes cannot execute
  // script in any current browser, and the classic CSS exfiltration channels
  // are already closed above by `default-src 'none'`, `img-src 'self' data:`
  // and `connect-src 'self'`. Crucially this does NOT loosen `style-src`, so
  // injected <style> blocks and external stylesheets remain blocked.
  "style-src-attr 'unsafe-inline'",
  // Astro's scoped styles and KaTeX ship as real stylesheets; element-level
  // <style> blocks stay hash-pinned via style-src-elem.
  `style-src-elem 'self' ${styleHashes.join(' ')}`,
  "img-src 'self' data:",
  "font-src 'self'",
  // Pagefind fetches its index and WASM from the same origin.
  "connect-src 'self'",
  "worker-src 'self' blob:",
  "manifest-src 'self'",
  "base-uri 'none'",
  "form-action 'none'",
  "frame-ancestors 'none'",
  'upgrade-insecure-requests',
].join('; ')

const out = `# Generated by scripts/gen-headers.mjs — do not edit by hand.
# Rules APPEND rather than override; use "! Header" to clear an inherited value.

/*
  Content-Security-Policy: ${csp}
  Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
  X-Content-Type-Options: nosniff
  Referrer-Policy: strict-origin-when-cross-origin
  Permissions-Policy: geolocation=(), microphone=(), camera=(), payment=(), usb=(), interest-cohort=()
  Cross-Origin-Opener-Policy: same-origin
  X-Frame-Options: DENY

# Content-hashed filenames can never change meaning, so revalidating them is
# pure waste. Clear the inherited value first, then set the immutable one.
/_astro/*
  ! Cache-Control
  Cache-Control: public, max-age=31536000, immutable

/pagefind/*
  ! Cache-Control
  Cache-Control: public, max-age=604800

/favicon.svg
  ! Cache-Control
  Cache-Control: public, max-age=604800
`

writeFileSync(join(DIST, '_headers'), out)
console.log(
  `_headers written · ${scriptHashes.length} inline script hash(es), ` +
    `${styleHashes.length} inline style hash(es)`,
)
